# Medical Notes Classification

Medical notes is an useful information source for patient data extraction. Notes classification is also an important task in Medical NLP domain. There are many techniques to solve this problem ranging from traditional method (Logistic Regression, SVM,...) to the state-of-the-art models (Transformer).

The below code block is the baseline model for a text classification problem in medical domain.

* Input: the corpus of medical transcriptions.
* Output: the type of each notes.

In this problem, we try to classify five labels:
* Surgery
* Consult - History and Phy.
* Cardiovascular / Pulmonary
* Orthopedic
* Others

The train-test split was also defined, please don't change our split.

Metric to evaluate: `f1_macro`

# Baseline Model Result


0.3729330560342061

                                precision    recall  f1-score   support

    Cardiovascular / Pulmonary       0.35      0.39      0.37       148
    Consult - History and Phy.       0.32      0.06      0.10       207
                    Orthopedic       0.39      0.14      0.21       142
                         Other       0.66      0.74      0.70      1055
                       Surgery       0.43      0.57      0.49       435

                      accuracy                           0.56      1987
                     macro avg       0.43      0.38      0.37      1987
                  weighted avg       0.54      0.56      0.53      1987

# Library & Data Loading

In [ ]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics


os.environ['CUDA_LAUNCH_BLOCKING'] = '1'


### PLEASE DON'T CHANGE ANYTHING IN THIS SECTION ###
DATA = "https://github.com/socd06/private_nlp/raw/master/data/mtsamples.csv"

filtered_labels = [
    "Surgery",
    "Consult - History and Phy.",
    "Cardiovascular / Pulmonary",
    "Orthopedic",
]
data = pd.read_csv(DATA, usecols=['medical_specialty', 'transcription']).dropna()
data.columns = ['labels', 'text']
data['labels'] = [i.strip() if (i.strip() in filtered_labels) else 'Other' for i in data.labels.to_list()]
train, test = train_test_split(data, test_size=0.4, stratify=data.labels, random_state=0)
train = train.reset_index(drop=True)
test = test.reset_index(drop=True)
### END ###

# My Model









In [ ]:
#create model
from TopicAllocate import Topic_Allocate
model = Topic_Allocate(vector_size= 300, segment_size = 40, segment_overlapping= 3)

In [ ]:
model.train(train['text'], train['labels'], batch_size= 32, epochs = 15, lr= 1e-3, wd= 1e-4)

Epoch [1/15], Step [94/94], Loss: 0.9979, f1: 0.2785
Epoch [2/15], Step [94/94], Loss: 0.9533, f1: 0.3474
Epoch [3/15], Step [94/94], Loss: 0.9876, f1: 0.3305
Epoch [4/15], Step [94/94], Loss: 0.9580, f1: 0.3432
Epoch [5/15], Step [94/94], Loss: 0.9839, f1: 0.4699
Epoch [6/15], Step [94/94], Loss: 0.9950, f1: 0.4433
Epoch [7/15], Step [94/94], Loss: 0.9962, f1: 0.4619
Epoch [8/15], Step [94/94], Loss: 0.9752, f1: 0.4172
Epoch [9/15], Step [94/94], Loss: 0.9562, f1: 0.4447
Epoch [10/15], Step [94/94], Loss: 0.9981, f1: 0.4212
Epoch [11/15], Step [94/94], Loss: 0.9074, f1: 0.4849
Epoch [12/15], Step [94/94], Loss: 0.9242, f1: 0.4700
Epoch [13/15], Step [94/94], Loss: 0.9884, f1: 0.4891
Epoch [14/15], Step [94/94], Loss: 0.9891, f1: 0.4878
Epoch [15/15], Step [94/94], Loss: 0.9946, f1: 0.4957


In [ ]:
import torch
from sklearn.metrics import confusion_matrix
Y_pred = model.predict(test['text'])
try:
  ypred = torch.argmax(Y_pred, dim = 1).cpu()
except:
  ypred = np.argmax(Y_pred, axis = 1)
Y_test = model.onehot_encoder.transform(np.array(test['labels'], dtype = type('string')).reshape(-1, 1))
ytest = np.argmax(Y_test, axis = 1)
print(confusion_matrix(ytest, ypred))
print(metrics.f1_score(ytest, ypred, average='macro'))
print(metrics.classification_report(ytest, ypred, target_names=list(model.onehot_encoder.categories_[0])))



[[ 71  21   0  16  40]
 [  4 144   2  57   0]
 [  0  21  80  13  28]
 [ 52 251  64 377 311]
 [ 36   1  67  13 318]]
0.4816267037046476
                            precision    recall  f1-score   support

Cardiovascular / Pulmonary       0.44      0.48      0.46       148
Consult - History and Phy.       0.33      0.70      0.45       207
                Orthopedic       0.38      0.56      0.45       142
                     Other       0.79      0.36      0.49      1055
                   Surgery       0.46      0.73      0.56       435

                  accuracy                           0.50      1987
                 macro avg       0.48      0.57      0.48      1987
              weighted avg       0.61      0.50      0.50      1987

