# Medical Notes Classification

Medical notes is an useful information source for patient data extraction. Notes classification is also an important task in Medical NLP domain. There are many techniques to solve this problem ranging from traditional method (Logistic Regression, SVM,...) to the state-of-the-art models (Transformer).

The below code block is the baseline model for a text classification problem in medical domain.

* Input: the corpus of medical transcriptions.
* Output: the type of each notes.

In this problem, we try to classify five labels:
* Surgery
* Consult - History and Phy.
* Cardiovascular / Pulmonary
* Orthopedic
* Others

The train-test split was also defined, please don't change our split.

Metric to evaluate: `f1_macro`

# Baseline Model Result


0.3729330560342061

                                precision    recall  f1-score   support

    Cardiovascular / Pulmonary       0.35      0.39      0.37       148
    Consult - History and Phy.       0.32      0.06      0.10       207
                    Orthopedic       0.39      0.14      0.21       142
                         Other       0.66      0.74      0.70      1055
                       Surgery       0.43      0.57      0.49       435

                      accuracy                           0.56      1987
                     macro avg       0.43      0.38      0.37      1987
                  weighted avg       0.54      0.56      0.53      1987

# Library & Data Loading

In [1]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics


os.environ['CUDA_LAUNCH_BLOCKING'] = '1'


### PLEASE DON'T CHANGE ANYTHING IN THIS SECTION ###
DATA = "https://github.com/socd06/private_nlp/raw/master/data/mtsamples.csv"

filtered_labels = [
    "Surgery",
    "Consult - History and Phy.",
    "Cardiovascular / Pulmonary",
    "Orthopedic",
]
data = pd.read_csv(DATA, usecols=['medical_specialty', 'transcription']).dropna()
data.columns = ['labels', 'text']
data['labels'] = [i.strip() if (i.strip() in filtered_labels) else 'Other' for i in data.labels.to_list()]
train, test = train_test_split(data, test_size=0.4, stratify=data.labels, random_state=0)
train = train.reset_index(drop=True)
test = test.reset_index(drop=True)
### END ###

# My Model









In [10]:
#create model
from TopicAllocate import Topic_Allocate
model = Topic_Allocate(vector_size= 500, segment_size = 20, segment_overlapping= 3)

In [11]:
model.train(train['text'], train['labels'], batch_size= 16, epochs = 30, lr= 1e-3, wd= 1e-4)

Epoch [1/30], Step [47/47], Loss: 0.9511, f1: 0.2474
Epoch [2/30], Step [47/47], Loss: 0.9453, f1: 0.2427
Epoch [3/30], Step [47/47], Loss: 0.9590, f1: 0.2566
Epoch [4/30], Step [47/47], Loss: 0.9776, f1: 0.2171
Epoch [5/30], Step [47/47], Loss: 0.9466, f1: 0.2654
Epoch [6/30], Step [47/47], Loss: 0.9251, f1: 0.3998
Epoch [7/30], Step [47/47], Loss: 0.9809, f1: 0.3463
Epoch [8/30], Step [47/47], Loss: 0.9521, f1: 0.3729
Epoch [9/30], Step [47/47], Loss: 0.9320, f1: 0.4252
Epoch [10/30], Step [47/47], Loss: 0.9401, f1: 0.4554
Epoch [11/30], Step [47/47], Loss: 0.9105, f1: 0.4611
Epoch [12/30], Step [47/47], Loss: 0.9233, f1: 0.4373
Epoch [13/30], Step [47/47], Loss: 0.9096, f1: 0.4640
Epoch [14/30], Step [47/47], Loss: 0.9132, f1: 0.4531
Epoch [15/30], Step [47/47], Loss: 0.9428, f1: 0.4409
Epoch [16/30], Step [47/47], Loss: 0.9032, f1: 0.4372
Epoch [17/30], Step [47/47], Loss: 0.9484, f1: 0.4741
Epoch [18/30], Step [47/47], Loss: 0.9180, f1: 0.4750
Epoch [19/30], Step [47/47], Loss: 0.

In [12]:
import torch
from sklearn.metrics import confusion_matrix
Y_pred = model.predict(test['text'])
try:
  ypred = torch.argmax(Y_pred, dim = 1).cpu()
except:
  ypred = np.argmax(Y_pred, axis = 1)
Y_test = model.onehot_encoder.transform(np.array(test['labels'], dtype = type('string')).reshape(-1, 1))
ytest = np.argmax(Y_test, axis = 1)
print(confusion_matrix(ytest, ypred))
print(metrics.f1_score(ytest, ypred, average='macro'))
print(metrics.classification_report(ytest, ypred, target_names=list(model.onehot_encoder.categories_[0])))



[[ 61  13   1  30  43]
 [  8 106   1  91   1]
 [  0   6  63  50  23]
 [ 42 144  34 566 269]
 [ 30   1  73  40 291]]
0.4867580375031094
                            precision    recall  f1-score   support

Cardiovascular / Pulmonary       0.43      0.41      0.42       148
Consult - History and Phy.       0.39      0.51      0.44       207
                Orthopedic       0.37      0.44      0.40       142
                     Other       0.73      0.54      0.62      1055
                   Surgery       0.46      0.67      0.55       435

                  accuracy                           0.55      1987
                 macro avg       0.48      0.51      0.49      1987
              weighted avg       0.59      0.55      0.55      1987

