# Medical Notes Classification

Medical notes is an useful information source for patient data extraction. Notes classification is also an important task in Medical NLP domain. There are many techniques to solve this problem ranging from traditional method (Logistic Regression, SVM,...) to the state-of-the-art models (Transformer).

The below code block is the baseline model for a text classification problem in medical domain.

* Input: the corpus of medical transcriptions.
* Output: the type of each notes.

In this problem, we try to classify five labels:
* Surgery
* Consult - History and Phy.
* Cardiovascular / Pulmonary
* Orthopedic
* Others

The train-test split was also defined, please don't change our split.

Metric to evaluate: `f1_macro`

# Baseline Model Result


0.3729330560342061

                                precision    recall  f1-score   support

    Cardiovascular / Pulmonary       0.35      0.39      0.37       148
    Consult - History and Phy.       0.32      0.06      0.10       207
                    Orthopedic       0.39      0.14      0.21       142
                         Other       0.66      0.74      0.70      1055
                       Surgery       0.43      0.57      0.49       435

                      accuracy                           0.56      1987
                     macro avg       0.43      0.38      0.37      1987
                  weighted avg       0.54      0.56      0.53      1987

# Library & Data Loading

In [7]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import metrics


os.environ['CUDA_LAUNCH_BLOCKING'] = '1'


### PLEASE DON'T CHANGE ANYTHING IN THIS SECTION ###
DATA = "https://github.com/socd06/private_nlp/raw/master/data/mtsamples.csv"

filtered_labels = [
    "Surgery",
    "Consult - History and Phy.",
    "Cardiovascular / Pulmonary",
    "Orthopedic",
]
data = pd.read_csv(DATA, usecols=['medical_specialty', 'transcription']).dropna()
data.columns = ['labels', 'text']
data['labels'] = [i.strip() if (i.strip() in filtered_labels) else 'Other' for i in data.labels.to_list()]
train, test = train_test_split(data, test_size=0.4, stratify=data.labels, random_state=0)
train = train.reset_index(drop=True)
test = test.reset_index(drop=True)
### END ###

# My Model









In [25]:
#create model
from TopicAllocate import Topic_Allocate
model = Topic_Allocate(vector_size= 500, segment_size = 20, segment_overlapping= 3)

In [26]:
model.train(train['text'], train['labels'], batch_size= 32, epochs = 20, lr= 1e-3, wd= 1e-4)

Epoch [1/20], Step [94/94], Loss: 0.9650, f1: 0.2619
Epoch [2/20], Step [94/94], Loss: 0.9407, f1: 0.2894
Epoch [3/20], Step [94/94], Loss: 0.9447, f1: 0.3335
Epoch [4/20], Step [94/94], Loss: 0.9173, f1: 0.3523
Epoch [5/20], Step [94/94], Loss: 0.9945, f1: 0.3565
Epoch [6/20], Step [94/94], Loss: 0.9971, f1: 0.3989
Epoch [7/20], Step [94/94], Loss: 0.9656, f1: 0.4198
Epoch [8/20], Step [94/94], Loss: 0.9588, f1: 0.3983
Epoch [9/20], Step [94/94], Loss: 0.9968, f1: 0.4486
Epoch [10/20], Step [94/94], Loss: 0.9995, f1: 0.3944
Epoch [11/20], Step [94/94], Loss: 0.9739, f1: 0.4282
Epoch [12/20], Step [94/94], Loss: 0.9778, f1: 0.4323
Epoch [13/20], Step [94/94], Loss: 0.9808, f1: 0.4713
Epoch [14/20], Step [94/94], Loss: 0.9833, f1: 0.4534
Epoch [15/20], Step [94/94], Loss: 0.9753, f1: 0.4673
Epoch [16/20], Step [94/94], Loss: 0.9911, f1: 0.4784
Epoch [17/20], Step [94/94], Loss: 0.9667, f1: 0.4753
Epoch [18/20], Step [94/94], Loss: 0.9937, f1: 0.4574
Epoch [19/20], Step [94/94], Loss: 0.

In [27]:
import torch
from sklearn.metrics import confusion_matrix
Y_pred = model.predict(test['text'])
try:
  ypred = torch.argmax(Y_pred, dim = 1).cpu()
except:
  ypred = np.argmax(Y_pred, axis = 1)
Y_test = model.onehot_encoder.transform(np.array(test['labels'], dtype = type('string')).reshape(-1, 1))
ytest = np.argmax(Y_test, axis = 1)
print(confusion_matrix(ytest, ypred))
print(metrics.f1_score(ytest, ypred, average='macro'))
print(metrics.classification_report(ytest, ypred, target_names=list(model.onehot_encoder.categories_[0])))



[[ 74  14   2  22  36]
 [  3 110  14  80   0]
 [  0   4  59  19  60]
 [ 52 155 101 458 289]
 [ 40   1  30  16 348]]
0.4810129061210914
                            precision    recall  f1-score   support

Cardiovascular / Pulmonary       0.44      0.50      0.47       148
Consult - History and Phy.       0.39      0.53      0.45       207
                Orthopedic       0.29      0.42      0.34       142
                     Other       0.77      0.43      0.56      1055
                   Surgery       0.47      0.80      0.60       435

                  accuracy                           0.53      1987
                 macro avg       0.47      0.54      0.48      1987
              weighted avg       0.61      0.53      0.53      1987

