# Medical Notes Classification

Medical notes is an useful information source for patient data extraction. Notes classification is also an important task in Medical NLP domain. There are many techniques to solve this problem ranging from traditional method (Logistic Regression, SVM,...) to the state-of-the-art models (Transformer).

The below code block is the baseline model for a text classification problem in medical domain.

* Input: the corpus of medical transcriptions.
* Output: the type of each notes.

In this problem, we try to classify five labels:
* Surgery
* Consult - History and Phy.
* Cardiovascular / Pulmonary
* Orthopedic
* Others

The train-test split was also defined, please don't change our split.

Metric to evaluate: `f1_macro`

# Baseline Model Result


0.3729330560342061

                                precision    recall  f1-score   support

    Cardiovascular / Pulmonary       0.35      0.39      0.37       148
    Consult - History and Phy.       0.32      0.06      0.10       207
                    Orthopedic       0.39      0.14      0.21       142
                         Other       0.66      0.74      0.70      1055
                       Surgery       0.43      0.57      0.49       435

                      accuracy                           0.56      1987
                     macro avg       0.43      0.38      0.37      1987
                  weighted avg       0.54      0.56      0.53      1987

# Library & Data Loading

In [1]:
!pip install -U transformers simpletransformers
!pip install tensorboardX
!pip install simpletransformers

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/usr/bin/python -m pip install --upgrade pip' command.
Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/usr/bin/python -m pip install --upgrade pip' command.
Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/usr/bin/python -m pip install --upgrade pip' command.


In [2]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics
from simpletransformers.classification import ClassificationModel, ClassificationArgs

os.environ['CUDA_LAUNCH_BLOCKING'] = '1'


### PLEASE DON'T CHANGE ANYTHING IN THIS SECTION ###
DATA = "https://github.com/socd06/private_nlp/raw/master/data/mtsamples.csv"

filtered_labels = [
    "Surgery",
    "Consult - History and Phy.",
    "Cardiovascular / Pulmonary",
    "Orthopedic",
]
data = pd.read_csv(DATA, usecols=['medical_specialty', 'transcription']).dropna()
data.columns = ['labels', 'text']
data['labels'] = [i.strip() if (i.strip() in filtered_labels) else 'Other' for i in data.labels.to_list()]
train, test = train_test_split(data, test_size=0.4, stratify=data.labels, random_state=0)
train = train.reset_index(drop=True)
test = test.reset_index(drop=True)
### END ###

2021-10-06 01:18:35.371094: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-10-06 01:18:35.371136: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


# Preprocessing

# My Model


In [3]:
#encode labels 
le = LabelEncoder()
train['labels'] = le.fit_transform(train.labels)
test['labels'] = le.transform(test.labels)

### Encode Text


In [4]:
#create model
import TopicAllocate as ta
model = ta.Topic_Allocate()

[nltk_data] Downloading package wordnet to /home/kienanh/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to /home/kienanh/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [5]:
#encode texts into matrix
X_train = np.asarray(model.doc2vec_s2v(train['text'], vector_size = 500, fit = True))
X_test = np.asarray(model.doc2vec_s2v(test['text'], vector_size = 500))


KeyboardInterrupt: 

In [ ]:
print(train['text'][0])
print(X_train[0].shape)

REVIEW OF SYSTEMS,GENERAL:  Negative weakness, negative fatigue, native malaise, negative chills, negative fever, negative night sweats, negative allergies.,INTEGUMENTARY:  Negative rash, negative jaundice.,HEMATOPOIETIC:  Negative bleeding, negative lymph node enlargement, negative bruisability.,NEUROLOGIC:  Negative headaches, negative syncope, negative seizures, negative weakness, negative tremor.  No history of strokes, no history of other neurologic conditions.,EYES:  Negative visual changes, negative diplopia, negative scotomata, negative impaired vision.,EARS:  Negative tinnitus, negative vertigo, negative hearing impairment.,NOSE AND THROAT:  Negative postnasal drip, negative sore throat.,CARDIOVASCULAR:  Negative chest pain, negative dyspnea on exertion, negative palpations, negative edema.  No history of heart attack, no history of arrhythmias, no history of hypertension.,RESPIRATORY:  No history of shortness of breath, no history of asthma, no history of chronic obstructive 

In [ ]:
# onehot labels
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

y_train = train['labels']

# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
Y_train = onehot_encoder.fit_transform(np.array(y_train).reshape(-1, 1))
Y_test = onehot_encoder.transform(np.array(test['labels']).reshape(-1,1))

# invert first example
inverted = le.inverse_transform([np.argmax(Y_train[0, :])])
print(inverted)

['Consult - History and Phy.']


### Train with LSTM

#### sequence -> vec

In [ ]:
#%% import library
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense, LSTM, Dropout

In [ ]:
max_size = np.amax(np.array([x.shape[0] for x in X_train]))
def fill_zeros(x, vector_size):
    missing = max_size - x.shape[0]
    fill_in = np.zeros((missing, vector_size))
    return np.vstack((fill_in, x))
func = lambda x: fill_zeros(x, 500)
X_train_lstm_s2v = np.array([func(x) for x in X_train])
X_test_lstm_s2v = np.array([func(x) for x in X_test])


In [ ]:
#%% Xay dung model LSTM
lstm_model = Sequential()
# Units: ???
# return_sequences: tra lai ket qua cuoi cho lop tiep theo
lstm_model.add(LSTM(units=50, return_sequences=True, input_shape=(X_train_lstm_s2v.shape[1], X_train_lstm_s2v.shape[2])))
# Dropout: bỏ 20% chống overhitting
lstm_model.add(Dropout(0.2))
# regressor.add(LSTM(units=50, return_sequences=True))
# regressor.add(Dropout(0.2))
# regressor.add(LSTM(units=50, return_sequences=True))
# regressor.add(Dropout(0.2))
lstm_model.add(LSTM(units=50))
lstm_model.add(Dropout(0.2))
lstm_model.add(Dense(units=5, activation="softmax"))
lstm_model.compile(optimizer="adam", loss="categorical_crossentropy",  metrics=["accuracy"])
lstm_model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_2 (LSTM)                (None, 182, 50)           110200    
_________________________________________________________________
dropout_2 (Dropout)          (None, 182, 50)           0         
_________________________________________________________________
lstm_3 (LSTM)                (None, 50)                20200     
_________________________________________________________________
dropout_3 (Dropout)          (None, 50)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 255       
Total params: 130,655
Trainable params: 130,655
Non-trainable params: 0
_________________________________________________________________


In [ ]:
lstm_model.fit(X_train_lstm_s2v, Y_train, epochs=50, batch_size=32, validation_split= 0.1)

2021-10-06 00:19:01.523891: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 975884000 exceeds 10% of free system memory.


Epoch 1/50
84/84 [==============================] - 43s 431ms/step - loss: 1.2933 - accuracy: 0.5496 - val_loss: 1.0656 - val_accuracy: 0.5638
Epoch 2/50
84/84 [==============================] - 26s 307ms/step - loss: 1.0629 - accuracy: 0.5537 - val_loss: 1.0727 - val_accuracy: 0.5604
Epoch 3/50
84/84 [==============================] - 30s 354ms/step - loss: 1.0750 - accuracy: 0.5466 - val_loss: 1.0570 - val_accuracy: 0.5738
Epoch 4/50
84/84 [==============================] - 21s 246ms/step - loss: 1.0382 - accuracy: 0.5659 - val_loss: 1.0668 - val_accuracy: 0.5302
Epoch 5/50
84/84 [==============================] - 30s 358ms/step - loss: 1.0429 - accuracy: 0.5577 - val_loss: 1.0569 - val_accuracy: 0.5369
Epoch 6/50
84/84 [==============================] - 35s 420ms/step - loss: 1.0071 - accuracy: 0.5422 - val_loss: 1.0128 - val_accuracy: 0.5503
Epoch 7/50
84/84 [==============================] - 29s 345ms/step - loss: 1.0102 - accuracy: 0.5675 - val_loss: 1.0203 - val_accuracy: 0.5537

In [ ]:
from sklearn.metrics import confusion_matrix
check = lstm_model.predict(X_test_lstm_s2v)
check = np.argmax(check, axis = 1)
ytrain = np.argmax(Y_test, axis = 1)
print(confusion_matrix(check, ytrain))
print(metrics.f1_score(ytrain, check, average='macro'))
print(metrics.classification_report(ytrain, check, target_names=list(le.classes_)))

2021-10-06 00:40:38.260557: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 723268000 exceeds 10% of free system memory.


[[ 33  29   0  50  30]
 [  7  27  12  96   0]
 [  1   8  35  40  49]
 [ 52 143  57 712 199]
 [ 55   0  38 157 157]]
0.3303601816063591
                            precision    recall  f1-score   support

Cardiovascular / Pulmonary       0.23      0.22      0.23       148
Consult - History and Phy.       0.19      0.13      0.15       207
                Orthopedic       0.26      0.25      0.25       142
                     Other       0.61      0.67      0.64      1055
                   Surgery       0.39      0.36      0.37       435

                  accuracy                           0.49      1987
                 macro avg       0.34      0.33      0.33      1987
              weighted avg       0.47      0.49      0.47      1987



#### word -> vec

In [ ]:
a = list([])
a.append("a")

In [ ]:
X_train_lstm_w2v = model.doc2vec_w2v(train['text'], vector_size = 500)
X_test_lstm_w2v = model.doc2vec_w2v(test['text'], vector_size = 500)

In [ ]:
X_train_lstm_w2v

KeyboardInterrupt: 

In [ ]:
X_train_lstm_w2v = np.asarray([])
model.w2v["he"]

AttributeError: 'Topic_Allocate' object has no attribute 'w2v'